version: '3.8'

services:
  craftcoin-node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./volume:/root/.craftcoin
      - ./craftcoin.conf:/root/.craftcoin/craftcoin.conf
    restart: unless-stopped
    network_mode: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
